package cn.shang.charging.generator;

/**
 * Feature switches used by the billing result generator.
 */
public enum TestFeature {
    UNIT_BASED,
    CONTINUOUS,
    CONTINUE,
    SCHEME_SWITCH,
    SEGMENT_LOCAL,
    GLOBAL_ORIGIN,
    QUERY_TIME,
    TIME_ROUNDING,
    SIMPLIFICATION,

    FREE_MINUTES,
    MULTI_PROMOTION,
    EXTERNAL_FREE_RANGE,
    EXTERNAL_FREE_MINUTES,
    BUBBLE_FREE_RANGE,
    START_FREE,
    CONDITIONAL_START_FREE,

    DAY_NIGHT_CROSS_PERIOD_UNIT,
    DAY_NIGHT_DAILY_CAP,
    DAY_NIGHT_MIXED_VALUE_SPEC,

    RELATIVE_MULTI_PERIOD,
    RELATIVE_CYCLE_CAP,

    COMPOSITE_NATURAL_PERIOD,
    COMPOSITE_CROSS_PERIOD_MODE,
    COMPOSITE_INSUFFICIENT_UNIT,

    FLAT_FREE
}
